### ISSUE TITLE
Feat: auto generate site meta info from url by GPT

### ISSUE THREAD

**Issue by cmsax** [cmsax/linka#8]

**Comment by use-the-fork** [comment]
So this had to be done as a double API Call since CORS is an issue with Fetch and Axious I used a third-party service (Browserless) to get the page content initially and then passed that info to OPEN AI to summarize.

**Comment by cmsax** [comment]
I've tested this new feature today, it worked and I found that the content return by GPT was truncated.

**Comment by use-the-fork** [comment]
@cmsax Try now. it seemed to have fixed the issue for me.

**Comment by cmsax** [comment]
It now works!
